### ISSUE TITLE
Como jugador quiero tener un mejor diseño del tutorial

### ISSUE THREAD

**Issue by HaoshuangHou** [Proyectos1-FDI-UCM/c2324-Grupo01#105]
- [ ] Si esta sincronizado
- [ ] Se entiende que hay que hacer
- [ ] Se puede pasar el nivel sin mucha dificultad

> https://github.com/Proyectos1-FDI-UCM/c2324-Grupo01/issues/113

> https://github.com/Proyectos1-FDI-UCM/c2324-Grupo01/issues/112

**Comment by bingoo30** [comment]
- [ ] Textos mas cortos con imagenes
- [ ] Trozos donde se enseñan las mecanicas
- [ ] Volver al checkpoint si el jugador muere
