### ISSUE TITLE
Cambiar menu de victoria

### ISSUE THREAD

**Issue by HaoshuangHou** [Proyectos1-FDI-UCM/c2324-Grupo01#124]
- [x] Mostrar las puntuaciones de cada objetos en vertical, y que aparezcan uno a uno
- [x] Las ¨estrellas¨ conseguida según la puntuación.

**Comment by bingoo30** [comment]
BING: el slider de la victoria funciona. Quizás el tiempo de aparicion de cada apartado de puntuación sea más larga
