### ISSUE TITLE
La cámara deja de seguir al jugador

### ISSUE THREAD

**Issue by DanieLauriaPal** [Proyectos1-FDI-UCM/c2324-Grupo01#144]
Al inicio de los niveles exclusivamente, antes de que la cámara siga al jugador, si usamos el deslizamiento en el momento exacto esto rompe el seguimiento de la cámara hasta que salgas del nivel.

Pasos
[Es más sencillo reproducirlo, como mostraré en el video, en los niveles lentos]
1.	Elige nivel.
2.	Comienza a pulsar repetidamente y rápidamente el deslice antes de que el personaje se mueva, (pulsar un botón o ambos a la vez).
3.	Si la cámara no sigue al personaje, lo has conseguido, (esto es algo que no sé exactamente como reproducirlo con un 100% de precisión, por eso es pulsar repetidamente y no en un momento justo).

Enlace al video:
https://drive.google.com/drive/folders/1huD0EBfcXpLdQR0ohL68Mcw9MnZKpEXA?usp=sharing

**Comment by HaoshuangHou** [comment]
Dado que este problema no es fácil de reproducir y depende de varios factores, no hemos podido identificar por qué se ha producido el fallo. Por lo tanto, hemos decidido dejar este problema.
