### ISSUE TITLE
Informe Bug: Selección de niveles

### ISSUE THREAD

**Issue by DanielRamos4722** [Proyectos1-FDI-UCM/c2324-Grupo01#146]
En ocasiones el juego se lanza directamente en la selección de niveles en vez de en el menú de inicio.

¿Orden de ejecución no especificado? En el 90% de los casos no ocurre.

![DM_Bug2](https://github.com/Proyectos1-FDI-UCM/c2324-Grupo01/assets/100843627/28cf87d0-29c4-411c-8600-d974b8cb3e93)

**Comment by HaoshuangHou** [comment]
Eso pasa cuando el jugador no sale del juego con el botón QUIT del menú principal, que según la lógica que tenemos si el usuario elige un nivel y sale desde ese nivel se cambia un variable que con el botón QUIT del menú principal se resetea. Si el jugador no sale del juego como se esperaba puede causar ese problema.
