### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by DanielRamos4722** [Proyectos1-FDI-UCM/c2324-Grupo01#147]
- Algo más de aire/pausa durante la sucesión de pop ups del tutorial para que se puedan leer sin preocuparse simultáneamente de la partida, podría hacerlo más entendible o incentivar más a leerlos.

- El nivel de Dear_X se siente considerablemente más fácil que Gnork Party debido a la velocidad (solo en caso de que se busque un escalado de dificultad en la progresión de niveles).

- Quizás utilizar Platform Effector en ciertos colliders para evitar un choque lateral.

**Comment by HaoshuangHou** [comment]
Con respecto a la observación sobre la diferencia de dificultad entre los niveles Dear_X y GnorkParty, hemos decidido cambiar el orden de los niveles, haciendo que GnorkParty sea el último nivel.

En cuanto a la observación sobre las plataformas, inicialmente habíamos implementado plataformas que no colisionan si el choque es lateral. Sin embargo, los jugadores que hemos puesto a probar el juego comentaron que esto resulta muy confuso y parece más un fallo que un efecto intencional de las plataformas. Por lo tanto, hemos decidido que es mejor tener plataformas normales y proporcionar vidas limitadas para dar más margen de error.
