### ISSUE TITLE
Las explicaciones del tutorial aparezcan cuando tienen que aparecer

### ISSUE THREAD

**Issue by HaoshuangHou** [Proyectos1-FDI-UCM/c2324-Grupo01#22]
Activar los textos de explicaciones en el tutorial cuando sea necesario.
-[] Si aparecen los textos cuando se colisiona con el objeto

-[]Si da tiempo para leer los textos

**Comment by hdebrito92** [comment]
Hacerlo de forma que el UIManager pueda ser usado en otros niveles o crear un UIManager propio de tutorial. No olvidarse de integrar con el GameManager
