### ISSUE TITLE
Como jugador quiero tener explicaciones en el tutorial

### ISSUE THREAD

**Issue by hdebrito92** [Proyectos1-FDI-UCM/c2324-Grupo01#3]
Poner textos que explican las mecánicas del juego
-[]Si se puede entender las cosas con los textos

**Comment by HaoshuangHou** [comment]
-[x]#22

**Comment by HaoshuangHou** [comment]
> https://github.com/orgs/Proyectos1-FDI-UCM/projects/21/views/2?pane=issue&itemId=55181269
