### ISSUE TITLE
Como jugador quiero ser recompensado con un multiplicador de puntuación al hacer acciones bien sin fallar (la lógica)

### ISSUE THREAD

**Issue by hdebrito92** [Proyectos1-FDI-UCM/c2324-Grupo01#88]
Internamente: Un número int
Cada tick, se reduce
Al hacer acciones bien, se le suma una cantidad fija
Al hacer acciones mal, se le resta una cantidad fija o se resetea (?)

Existen ciertos rangos que determinan el multiplicador en el que estás (100, 200, etc.), el cual multiplica la puntuación que obtienes por cualquier cosa

Visualmente: Una barra y un coeficiente
La barra se rellena en base al valor interno con un máximo situado en el rango del próximo multiplicador
Si pasas al siguiente multiplicador, la barra se vacía y empieza desde ese multiplicador, hasta al siguiente, con un nuevo color
El coeficiente muestra el multiplicador (mientras no sea 1x, que es por defecto)

**Comment by GabrielBarrosoBuenoUCM** [comment]
- Añadir ComboManager sobre GameManager
- Todas (?) las acciones otorgan combo. En el caso de ganar puntos negativos, se resta al combo esos puntos * comboPenaltyMultiplier (serializado)
- El combo es un valor interno que progresa hasta determinadas cantidades (thresholds), y una vez las supera se cambia el multiplicador al correspondiente. Esto está serializado, por ahora hay 3 multiplicadores y se pueden añadir más cambiando la lógica

**Comment by bingoo30** [comment]
Cuando fallo en algo (por ejemplo, no he roto una caja), no me lleva al multiplicador inicial
