### ISSUE TITLE
Como jugador quiero introducción de la historia

### ISSUE THREAD

**Issue by HaoshuangHou** [Proyectos1-FDI-UCM/c2324-Grupo01#9]
Cinemática para introducir la historia

**Comment by GabrielBarrosoBuenoUCM** [comment]
- [ ] Cinemática de entrada la primera vez que se inicia el tutorial en una escena independiente
- [ ] Introducir el "antagonista" y la maldición
- [ ] Botón de skip durante la cinemática que aparezca después de pulsar botones lo suficiente o después de 3 segundos
- [ ] Botón en el menú principal para volver a ver la cinemática al lado del tutorial
